# make_stub_files: Thu 25 Jul 2019 at 22:35:06

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ST7735R:
    def __init__(self, spi: Any, dc: Any, cs: Any, rst: Any=None, width: Any=128, height: Any=128, ofx: Any=0, ofy: Any=0) -> None: ...
    def _block(self, x0: Any, y0: Any, x1: Any, y1: Any, data: Any=None) -> Any: ...
        #   0: return self._read(self._RAM_READ,x1-x0+1*y1-y0+1*size)
        # ? 0: return self._read(self._RAM_READ, x1-x0+number*y1-y0+number*size)
    def _encode_pos(self, a: str, b: Any) -> Any: ...
        #   0: return ustruct.pack(self._ENCODE_POS,a,b)
        # ? 0: return ustruct.pack(self._ENCODE_POS, str, b)
    def _encode_pixel(self, color: Any) -> Any: ...
        #   0: return ustruct.pack(self._ENCODE_PIXEL,self.color565(color))
        # ? 0: return ustruct.pack(self._ENCODE_PIXEL, self.color565(color))
    def _decode_pixel(self, data: Any) -> Any: ...
        #   0: return color565(*ustruct.unpack(self._DECODE_PIXEL,data))
        # ? 0: return color565(*ustruct.unpack(self._DECODE_PIXEL, data))
    def pixel(self, x: Any, y: Any, color: Any=None) -> Optional[Any]: ...
        #   0: return self._decode_pixel(self._block(x,y,x,y))
        # ? 0: return self._decode_pixel(self._block(x, y, x, y))
        #   1: return
        #   1: return
    def fill_rectangle(self, x: Any, y: Any, width: Any, height: Any, color: Any, N: Any=1) -> None: ...
    def fill(self, color: Any=0, N: Any=16) -> None: ...
    def hline(self, x: Any, y: Any, width: Any, color: Any, N: Any=1) -> None: ...
    def vline(self, x: Any, y: Any, height: Any, color: Any, N: Any=1) -> None: ...
    def blit_buffer(self, buffer: Any, x: Any, y: Any, width: Any, height: Any) -> None: ...
    def reset(self) -> None: ...
    def _write(self, command: Any=None, data: Any=None) -> None: ...
    def _read(self, command: Any=None, count: Any=0) -> Any: ...
        #   0: return data
        # ? 0: return data
    def color565(self, r: Any, g: Any=None, b: Any=None) -> Any: ...
        #   0: return r&248<<8|g&252<<3|b>>3
        # ? 0: return r&number<<number|g&number<<number|b>>number
