# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Finger:
    def __init__(self) -> None: ...
    def _monitor(self) -> None: ...
    def addUser(self, user_id: Any, access: Any, state: Any=1) -> None: ...
    def readUser(self) -> None: ...
    def readFingerCb(self, callback: Any) -> None: ...
    def getUnknownCb(self, callback: Any) -> None: ...
    def removeUser(self, user_id: Any) -> None: ...
    def removeAllUser(self) -> None: ...
    def _write(self, cmd: Any, q1: Any, q2: Any, q3: Any) -> None: ...
    def deinit(self) -> None: ...
