# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Joystick:
    def __init__(self, addr: Any=94) -> None: ...
    def _available(self) -> None: ...
    def X(self) -> Any: ...
        #   0: return self.value[2]|self.value[3]<<8
        # ? 0: return self.value[number]|self.value[number]<<number
    def Y(self) -> Any: ...
        #   0: return self.value[0]|self.value[1]<<8
        # ? 0: return self.value[number]|self.value[number]<<number
    def InvertX(self) -> Any: ...
        #   0: return 1024-self.X
        # ? 0: return number-self.X
    def InvertY(self) -> Any: ...
        #   0: return 1024-self.Y
        # ? 0: return number-self.Y
    def Press(self) -> Union[Any, number]: ...
    def _update(self) -> None: ...
    def setLed(self, num: Any, color: Any) -> None: ...
    def deinit(self) -> None: ...
