# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Keyboard:
    def __init__(self, addr: Any=8) -> None: ...
    def _available(self) -> None: ...
    def _update(self) -> None: ...
    def deinit(self) -> None: ...
    def readStr(self) -> Any: ...
        #   0: return self._str
        # ? 0: return self._str
    def clearStr(self) -> None: ...
    def deleteStrLast(self) -> None: ...
    def readKey(self) -> Union[Any, number]: ...
        #   0: return 0
        #   0: return number
        #   1: return data
        # ? 1: return data
    def isNewKeyPress(self) -> bool: ...
