# make_stub_files: Wed 10 Jul 2019 at 01:56:54

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def server_handshake(sock: Any) -> None: ...
def client_handshake(sock: Any) -> None: ...
