
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Align(Enum): ...
class Button(Enum): ...
class Color(Enum): ...
class Port(Enum): ...
class Direction(Enum): ...
class Stop(Enum): ...
class ImageFile(Enum): ...
class SoundFile(Enum): ...
