
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Align: ...
class Button: ...
class Color: ...
class Port: ...
class Direction: ...
class Stop: ...
class ImageFile: ...
class SoundFile: ...
