# make_stub_files: Wed 04 Sep 2019 at 21:10:42

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Align: ...
class Button: ...
class Color: ...
class Port: ...
class Direction: ...
class Stop: ...
class ImageFile: ...
class SoundFile: ...
