
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class TokenInfo(namedtuple(Tuple[, , , , ])):
    def __str__(self) -> Any: ...
        #   0: return %(self.type, tok_name[self.type], self.string, self.line)
        # ? 0: return %Tuple[self.type, tok_name[self.type], self.string, self.line]
def get_indent(l: Any) -> Tuple[int, Any]: ...
def tokenize(readline: Any) -> None: ...
