# make_stub_files: Tue 09 Jul 2019 at 15:35:54

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Lock:
    def __init__(self) -> None: ...
    def release(self) -> None: ...
    def acquire(self) -> bool: ...
