# make_stub_files: Mon 02 Sep 2019 at 04:29:51

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Lock:
    def __init__(self) -> None: ...
    def release(self) -> None: ...
    def acquire(self) -> bool: ...
