
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Buffer(object):
    def __init__(self, w: Any, h: Any) -> None: ...
    def pixel(self, x: Any, y: Any, color: Any) -> None: ...
    def save(self, filename: str) -> None: ...
def get_template(font: Any, size: Any, characters: Any=None) -> None: ...
def pack(font: Any, w: Any, h: Any) -> Any: ...
    #   0: return font_
    # ? 0: return font_
def text(buffer: Any, string: Any, font: Any, x0: Any=0, y0: Any=0, color: Any=(255, 255, 255), bgcolor: Any=(0, 0, 0), colors: Any=None) -> None: ...
def generate_font(font: Any, size: Any, file: Any=bool, characters: Any=None, font_name: Any=None) -> Tuple[Any, Any, Any]: ...
def generate_oled_font(font: Any, size: Any, characters: Any=None) -> Any: ...
    #   0: return out
    # ? 0: return out
