
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Calc:
    def __init__(self, addr: Any=8) -> None: ...
    def _available(self) -> None: ...
    def _update(self) -> None: ...
    def readStr(self) -> Any: ...
        #   0: return self.string[:]
        # ? 0: return self.string[:]
    def readKey(self) -> Union[Any, number]: ...
        #   0: return 0
        #   0: return number
        #   1: return data[0]
        # ? 1: return data[number]
    def clearStr(self) -> None: ...
    def deleteStrLast(self) -> None: ...
    def isNewKeyPress(self) -> bool: ...
    def deinit(self) -> None: ...
