# make_stub_files: Fri 26 Jul 2019 at 03:02:41

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ALSPT19(object):
    def __init__(self, pin_name: Any) -> None: ...
    def calibrate(self, samples: Any=300) -> None: ...
    def is_on(self) -> bool: ...
