
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class sound:
    def beep(frequency: int=, duration: int=, volume: int=) -> None: ...
    def beeps(number: int) -> None: ...
    def file(file_name: Union[(str, SoundFile)], volume: int=) -> None: ...
class display:
    def clear() -> None: ...
    def image(file_name: Union[(str, ImageFile)], alignment: Align=Align.CENTER, coordinate: Tuple[(int, int)]=, clear: bool=) -> None: ...
    def text(text: str, coordinate: Tuple[(int, int)]=) -> None: ...
class battery:
    def current() -> None: ...
    def voltage() -> None: ...
def buttons() -> List: ...
def light(color: Color) -> None: ...
