
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def S_IMODE(mode: Any) -> Any: ...
    #   0: return mode&
    # ? 0: return mode&
def S_IFMT(mode: Any) -> Any: ...
    #   0: return mode&
    # ? 0: return mode&
def S_ISDIR(mode: Any) -> bool: ...
def S_ISCHR(mode: Any) -> bool: ...
def S_ISBLK(mode: Any) -> bool: ...
def S_ISREG(mode: Any) -> bool: ...
def S_ISFIFO(mode: Any) -> bool: ...
def S_ISLNK(mode: Any) -> bool: ...
def S_ISSOCK(mode: Any) -> bool: ...
def filemode(mode: Any) -> Any: ...
    #   0: return .join(perm)
    # ? 0: return .join(perm)
