# make_stub_files: Wed 04 Sep 2019 at 21:10:42

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def print(*value) -> None: ...
def wait(time: int) -> None: ...
class StopWatch:
    def time(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def reset(self) -> None: ...
