# make_stub_files: Wed 17 Jul 2019 at 02:33:02

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class LS:
    def __repr__(self) -> str: ...
    def __call__(self, path: Any='.') -> None: ...
class PWD:
    def __repr__(self) -> Any: ...
        #   0: return os.getcwd()
        # ? 0: return os.getcwd()
    def __call__(self) -> Any: ...
        #   0: return self.__repr__()
        # ? 0: return self.__repr__()
class CLEAR:
    def __repr__(self) -> str: ...
    def __call__(self) -> Any: ...
        #   0: return self.__repr__()
        # ? 0: return self.__repr__()
def head(f: Any, n: int=10) -> None: ...
def cat(f: Any) -> None: ...
def newfile(path: Any) -> None: ...
class Man:
    def __repr__(self) -> str: ...
