# make_stub_files: Mon 02 Sep 2019 at 04:16:37

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def server_handshake(sock: Any) -> None: ...
def client_handshake(sock: Any) -> None: ...
