# make_stub_files: Wed 19 Jun 2019 at 14:54:52

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def server_handshake(sock: Any) -> None: ...
def client_handshake(sock: Any) -> None: ...
