# make_stub_files: Mon 02 Sep 2019 at 04:45:23

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ALSPT19(object):
    def __init__(self, pin_name: Any) -> None: ...
    def calibrate(self, samples: Any=300) -> None: ...
    def is_on(self) -> bool: ...
