
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class ALSPT19(object):
    def __init__(self, pin_name: Any) -> None: ...
    def calibrate(self, samples: Any=) -> None: ...
    def is_on(self) -> None: ...
