# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Dac:
    def __init__(self, port: Any, addr: Any=96) -> None: ...
    def _available(self) -> None: ...
    def writeData(self, data: Any, save: Any=bool) -> None: ...
    def setVoltage(self, vol: Any, save: Any=bool) -> None: ...
    def deinit(self) -> None: ...
