
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Rgb_multi:
    def __init__(self, port: Any, number: Any=143) -> None: ...
    def setColor(self, num: Any, color_in: Any) -> None: ...
    def setColorFrom(self, begin: Any, end: Any, color_in: Any) -> None: ...
    def setColorAll(self, color_in: Any) -> None: ...
    def setBrightness(self, brightness: Any) -> None: ...
    def deinit(self) -> None: ...
