# make_stub_files: Wed 10 Jul 2019 at 03:41:51

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Lock:
    def __init__(self) -> None: ...
    def release(self) -> None: ...
    def acquire(self) -> bool: ...
