# make_stub_files: Mon 02 Sep 2019 at 04:16:29

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class TokenInfo(namedtuple(str, Tuple[str, str, str, str, str])):
    def __str__(self) -> str: ...
def get_indent(l: Any) -> Tuple[int, Any]: ...
def get_str(l: Any, readline: Any) -> Tuple[str, Any, Any]: ...
def tokenize(readline: Any) -> None: ...
