
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class GFX_:
    def __init__(self, pixel: Any, size: Any) -> None: ...
    def write(self, text: Any, pos: Any, font: Any=ubuntu_mono_15, *args, **kwargs) -> None: ...
    def char(self, text: Any, pos: Any, font: Any=ubuntu_mono_15, *args, **kwargs) -> None: ...
    def __getattr__(self, attr: Any) -> Any: ...
        #   0: return getattr(self.display,attr)
        # ? 0: return getattr(self.display, attr)
        #   1: return getattr(self.gfx,attr)
        # ? 1: return getattr(self.gfx, attr)
class SSD1306(GFX_):
    def __init__(self, scl: Any, sda: Any, rst: Any=, size: Any=(, )) -> None: ...
class ST7735R(GFX_):
    def __init__(self, dc: Any, cs: Any, rst: Any, sclk: Any, mosi: Any, miso: Any, size: Any=(, ), offset: Any=(, )) -> None: ...
    def close(self) -> None: ...
