
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Write:
    def __init__(self, buffer: Any, font: Any) -> None: ...
    def text(self, string: Any, x0: Any=, y0: Any=, color: Any=, bgcolor: Any=, colors: Any=) -> None: ...
    def char(self, c: Any, x0: Any=, y0: Any=, color: Any=, bgcolor: Any=, colors: Any=) -> None: ...
    def draw(self, X: Any, Y: Any, col: Any, row: Any, buffer: Any) -> None: ...
