# make_stub_files: Thu 25 Jul 2019 at 22:35:06

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Write:
    def __init__(self, buffer: Any, font: Any) -> None: ...
    def text(self, string: Any, x0: Any=0, y0: Any=0, color: Any='#ffffff', bgcolor: Any=None, colors: Any=None) -> None: ...
    def char(self, c: Any, x0: Any=0, y0: Any=0, color: Any='#ffffff', bgcolor: Any=None, colors: Any=None) -> number: ...
    def draw(self, X: Any, Y: Any, col: Any, row: Any, buffer: Any) -> None: ...
