# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Gps:
    def __init__(self, port: Any) -> None: ...
    def _monitor(self) -> None: ...
    def deinit(self) -> None: ...
