
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Ir:
    def __init__(self, port: Any) -> None: ...
    def _irq_cb(self, pin: machine.Pin) -> None: ...
    def _update(self, arg: Any) -> None: ...
    def rxStatus(self) -> number: ...
    def txOn(self) -> None: ...
    def txOff(self) -> None: ...
    def deinit(self) -> None: ...
