# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Ncir:
    def __init__(self, port: Any) -> None: ...
    def _available(self) -> None: ...
    def temperature(self) -> Any: ...
        #   0: return round(tmp,2)
        # ? 0: return round(tmp, number)
    def deinit(self) -> None: ...
