# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Servo:
    def __init__(self, port: Any, freq: Any=50, min_us: Any=500, max_us: Any=2500, angle: Any=180) -> None: ...
    def write_us(self, us: smallint) -> None: ...
    def write_angle(self, degrees: Any=None, radians: Any=None) -> None: ...
    def deinit(self) -> None: ...
