
from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Weight:
    def __init__(self, port: Any) -> None: ...
    def zero(self) -> None: ...
    def rawData(self) -> Union[Any, number]: ...
        #   0: return 0
        #   0: return number
        #   1: return count
        # ? 1: return count
    def weight(self) -> Any: ...
        #   0: return countdata
        # ? 0: return countdata
    def _rawWeight(self) -> int: ...
    def deinit(self) -> None: ...
