# make_stub_files: Thu 20 Jun 2019 at 18:34:57

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Calibrate:
    def __init__(self, tft: Any) -> None: ...
    def drawCrossHair(self, x: Any, y: Any, clr: Any) -> None: ...
    def readCoordinates(self) -> Union[Tuple[Any, Any], Tuple[bool, bool]]: ...
    def calibrate(self, x: Any, y: Any, i: int) -> bool: ...
    def calibError(self) -> None: ...
    def tpcalib(self, save: Any=bool) -> Optional[Union[Tuple[Any, Any], bool]]: ...
