# make_stub_files: Sat 31 Aug 2019 at 04:45:32

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Align: ...
class Button: ...
class Color: ...
class Port: ...
class Direction: ...
class Stop: ...
class ImageFile: ...
class SoundFile: ...
