# make_stub_files: Sat 31 Aug 2019 at 04:45:32

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def print(*value) -> None: ...
def wait(time: int) -> None: ...
class StopWatch:
    def time(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def reset(self) -> None: ...
