# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class LidarStep:
    def __init__(self) -> None: ...
    def setRgb(self, color_in: Any, direction: Any=None) -> None: ...
    def setOneRgb(self, num: Any, color_in: Any) -> None: ...
    def goAhead(self, speed: Any) -> None: ...
    def goBack(self, speed: Any) -> None: ...
    def turnLeft(self, speed: Any) -> None: ...
    def turnRight(self, speed: Any) -> None: ...
    def controlWheel(self, X: Any, Y: Any) -> None: ...
    def setStepMotor(self, speedX: Any, speedY: Any, speedZ: Any, speedA: Any) -> None: ...
    def setServo(self, num: Any, angle: Any) -> None: ...
class LidarBot(LidarStep):
    def __init__(self) -> None: ...
    def deinit(self) -> None: ...
