# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Lorawan:
    def __init__(self) -> None: ...
    def _monitor(self) -> None: ...
    def _uart_cb(self, res: Any) -> None: ...
    def _reset(self) -> number: ...
    def _write(self, data: Any) -> None: ...
    def _setMode(self, mode: Any) -> None: ...
    def _waitTimeout(self, t: Any) -> number: ...
    def initP2PMode(self, frq: Any, sp: Any=12, bw: Any=500, preTx: Any=8, preRx: Any=8, power: Any=17) -> None: ...
    def initRxMode(self, callback: Any=None) -> None: ...
    def txStr(self, sr: Any) -> None: ...
    def deinit(self) -> None: ...
