# make_stub_files: Tue 03 Sep 2019 at 17:05:43

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
class Servo:
    def __init__(self, min_us: Any=500, max_us: Any=2500) -> None: ...
    def _available(self) -> None: ...
    def write_us(self, pos: Any, us: smallint) -> None: ...
    def write_angle(self, pos: Any, angle: Any) -> None: ...
    def deinit(self) -> None: ...
