# make_stub_files: Wed 17 Jul 2019 at 02:38:14

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def server_handshake(sock: Any) -> None: ...
def client_handshake(sock: Any) -> None: ...
