# make_stub_files: Fri 21 Jun 2019 at 00:44:00

from typing import Any, Dict, Optional, Sequence, Tuple, Union
Node = Any
def server_handshake(sock: Any) -> None: ...
def client_handshake(sock: Any) -> None: ...
