name: Deploy Packages

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions'
    env:
      GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Fetch History
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@v1.1.0
        with:
          python-version: "3.7.x"

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.0.3

      - name: Setup Environment
        run: |
          poetry install -v
          poetry run pre-commit

      - name: Build Packages
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          poetry run ./main.py generate --update
          git status -vv

      - name: Commit Changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -a -m "chore: Update All Frozen" || true

      - name: Push Changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.actor != 'github-actions'
    env:
      GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          ref: master

      - uses: actions/setup-python@v1.1.0
        with:
          python-version: "3.7.x"

      - name: Install Poetry
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.0.3

      - name: Setup Environment
        run: |
          poetry install -v
          poetry run pre-commit

      - name: Update Package Branches
        run: |
          git config user.email "action@github.com"
          git config user.name "github-actions"
          git remote rm origin || true
          git remote add origin "https://x-access-token:${{ secrets.GIT_PAT }}@github.com/bradenm/micropy-stubs.git"
          poetry run ./main.py archive --all --commit
          git status

      - name: Push Changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
