name: Deploy Packages

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Setup Environment
        run: |
          git checkout master
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Build Packages
        run: pipenv run ./main.py generate --update

      - name: Commit Changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: Update All Frozen" -a

      - name: Push Changes
        uses: ad-m/github-push-action@v.0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Setup Environment
        run: |
          git checkout master
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Update Package Branches
        run: pipenv run ./main.py archive --all --commit

      - name: Push Changes
        uses: ad-m/github-push-action@v.0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
