name: Deploy Packages

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    env:
      GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_PAT }}

      - name: Fetch History
        run: git fetch --prune --unshallow

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.6

      - name: Setup Environment
        run: |
          poetry install -v
          poetry run pre-commit

      - name: Build Packages
        env:
          GIT_PAT: ${{ secrets.GIT_PAT }}
        run: |
          poetry run ./main.py generate --update
          git status -vv

      - name: Commit Changes
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "chore: Update All Frozen [skip ci]" || true

      - name: Push Changes
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.actor != 'github-actions[bot]' && github.event_name != 'pull_request'
    env:
      GIT_PAT: ${{ secrets.GIT_PAT }}

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GIT_PAT }}
          fetch-depth: 0
          ref: master

      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.x"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.6

      - name: Setup Environment
        run: |
          poetry install -v
          poetry run pre-commit

      - name: Update Package Branches
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote rm origin || true
          git remote add origin "https://x-access-token:${{ secrets.GIT_PAT }}@github.com/bradenm/micropy-stubs.git"
          poetry run ./main.py archive --all --commit
          git status

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
