name: Deploy Packages

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Setup Environment
        run: |
          git checkout master
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Build Packages
        run: pipenv run ./main.py generate --update

      - name: Commit Changes
        if: github.ref == 'refs/heads/master'
        run: |
          git add .
          git commit -m "chore: Update All Frozen"
          git push origin master

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Setup Environment
        run: |
          git checkout master
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Update Package Branches
        run: pipenv run ./main.py archive --all --commit

      - name: Push Changes
        if: github.ref == 'refs/heads/master'
        run: git push origin master
