name: Deploy Production Repo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1
      - name: Setup Environment
        run: pipenv install --dev
      - name: Generate Archives
        run: pipenv run ./main.py archive --clean --all

      - name: Upload Packages
        uses: peter-evans/s3-backup@v1.0.0
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          MIRROR_TARGET: micropy-stubs-prod/packages
          MIRROR_SOURCE: dist
        with:
          args: --overwrite --remove
