name: Deploy Packages

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * mon"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'GitHub Action'
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1.1.0
        with:
          python-version: "3.7.x"
      - uses: dschep/install-pipenv-action@v1

      - name: Setup Environment
        run: |
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Build Packages
        run: pipenv run ./main.py generate --update

      - name: Commit Changes
        if: github.ref == 'refs/heads/master'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "chore: Update All Frozen" -a || true

      - name: Push Changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@v.0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.actor != 'GitHub Action'
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: actions/setup-python@v1.1.0
        with:
          python-version: "3.7.x"
      - uses: dschep/install-pipenv-action@v1

      - name: Setup Environment
        run: |
          git checkout master
          git fetch
          pipenv install --dev
          pipenv run pre-commit

      - name: Update Package Branches
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote rm origin || true
          git remote add origin https://x-access-token:${{ secrets.GIT_API_TOKEN }}@github.com/bradenm/micropy-stubs.git
          pipenv run ./main.py archive --all --commit

      - name: Push Changes
        uses: ad-m/github-push-action@v.0.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
