name: Deploy Packages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_API_TOKEN: ${{ secrets.GIT_API_TOKEN }}

    steps:
      - uses: actions/checkout@master
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - uses: actions/setup-python@v1
      - uses: dschep/install-pipenv-action@v1

      - name: Setup Environment
        run: pipenv install --dev

      - name: Update All Packages
        run: pipenv run ./main.py generate --update

      - name: Update Package Branches
        if: github.ref == 'master'
        run: pipenv run ./main.py archive --all --commit

      - name: Push Changes
        if: github.ref == 'master'
        run: git push origin master
